refactor: make text_config accept qualified names (#160)
Previously, parameter `text_config` did not accept qualified names
because we didn't split them before passing them to
`get_ts_config_oid()`.

```sql
steve=# create index idx on test using bm25 (content) with (text_config = 'pg_catalog.english');
NOTICE:  BM25 index build started for relation idx
ERROR:  text search configuration "pg_catalog.english" does not exist
```

Fixes #156. Regression test added, see `test/sql/text_config.sql`.